

final Map<String, List<String>> interestCategories = {
  'Education': [
    'NIOS',
    'Online Learning',
    'School Life',
    'College Students',
    'Tuition & Coaching',
    'Skill Development',
    'Competitive Exams (NEET, UPSC, SSC)',
    'Spoken English',
    'Study Abroad',
  ],
  'Technology': [
    'Smartphones',
    'Mobile Apps',
    'Gadgets',
    'Internet Tips',
    'Digital Payments',
    'AI & ChatGPT',
    'Coding / Programming',
    'Web Development',
    'Ethical Hacking',
  ],
  'Lifestyle': [
    'Travel',
    'Fashion',
    'Health & Fitness',
    'Beauty & Makeup',
    'Food & Cooking',
    'Photography',
    'Parenting',
    'Journaling',
    'Minimalism',
  ],
  'Entertainment': [
    'Gaming (Mobile/PC/Console)',
    'Anime',
    'Cartoons',
    'Memes & Funny Videos',
    'Movies',
    'TV Shows',
    'Stand-up Comedy',
    'Music & Singing',
    'Dance & Reels',
  ],
  'Career & Money': [
    'Government Jobs',
    'Part-time Jobs',
    'Freelancing',
    'Internships',
    'Work From Home',
    'Side Hustles',
    'Resume Building',
    'Business Ideas',
    'Investment & Savings',
  ],
  'Social & Media': [
    'WhatsApp Status',
    'YouTube Shorts / Vlogs',
    'Instagram Reels',
    'TikTok (if regionally used)',
    'Snapchat Content',
    'ShareChat Content',
    'Influencer Marketing',
    'Affiliate Marketing',
    'Blogging & Vlogging',
  ],
  'Personal Growth': [
    'Motivation',
    'Time Management',
    'Goal Setting',
    'Self-Discipline',
    'Public Speaking',
    'Meditation / Mindfulness',
    'Productivity Tools',
    'Reading / Book Summaries',
  ],
  'Regional & Cultural': [
    'Malayalam Content',
    'Tamil Content',
    'Hindi Content',
    'Kerala Local News',
    'Tamil Nadu Updates',
    'Indian Culture & Festivals',
    'Village Life',
    'Art & Handicrafts',
  ],
  'Wellbeing & Awareness': [
    'Mental Health',
    'Physical Wellness',
    'Clean Living',
    'Women\'s Health',
    'Youth Guidance',
    'Toxic Parenting Awareness',
    'Study Motivation',
  ],
};
